// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2832.Robot2017;

import com.ctre.CANTalon;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainLeftFront;
    public static CANTalon driveTrainRightFront;
    public static CANTalon driveTrainLeftRear;
    public static CANTalon driveTrainRightRear;
    public static CANTalon climbMotor1;
    public static CANTalon climbMotor2;
    public static CANTalon shooterShootMotor;
    public static CANTalon shooterFeeder;
    public static CANTalon ballIntakeMotor;
    public static CANTalon ballIntakeLift;
    public static Solenoid gearIntakeRamp;
    public static Solenoid gearScorePusher;
    public static Solenoid gearScoreDoor1;
    public static Solenoid gearScoreDoor2;
    public static RobotDrive driveTrainRobotDrive41;
    public static Relay lightsLightEnable;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFront = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "LeftFront", driveTrainLeftFront);
        driveTrainRightFront = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "RightFront", driveTrainRightFront);
        driveTrainLeftRear = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "LeftRear", driveTrainLeftRear);
        driveTrainRightRear = new CANTalon(4);
        LiveWindow.addActuator("DriveTrain", "RightRear", driveTrainRightRear);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFront, driveTrainLeftRear,
                driveTrainRightFront, driveTrainRightRear);
		driveTrainRobotDrive41.setSafetyEnabled(true);
		driveTrainRobotDrive41.setExpiration(0.1);
		driveTrainRobotDrive41.setSensitivity(0.5);
		driveTrainRobotDrive41.setMaxOutput(1.0);
          
        climbMotor1 = new CANTalon(5);
        LiveWindow.addActuator("Climbing", "Motor1", climbMotor1);
        climbMotor2 = new CANTalon(6);
        LiveWindow.addActuator("Climbing", "Motor2", climbMotor2);
        
        shooterShootMotor = new CANTalon(7);
        LiveWindow.addActuator("Shooter", "Shoot", shooterShootMotor);
        shooterFeeder = new CANTalon(8);
        LiveWindow.addActuator("Shooter", "Feeder", shooterFeeder);
        
        ballIntakeMotor = new CANTalon(9);
        LiveWindow.addActuator("BallIntake", "Intake", ballIntakeMotor);
        ballIntakeLift = new CANTalon(10);
        LiveWindow.addActuator("BallIntake", "Lift", ballIntakeLift);
        

        lightsLightEnable = new Relay(0);
        LiveWindow.addActuator("Lights", "LightEnable", lightsLightEnable);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
